### ISSUE TITLE
Problems on the site after publication in Zyro

### ISSUE THREAD

**Issue by Alienson402** [hostinger/zyro-sdk-php#4]
![222](https://cloud.githubusercontent.com/assets/20923036/24898914/20db4236-1ea7-11e7-817f-cda55d4a972a.jpg)

After the publication, the access rights to files are violated.
![333](https://cloud.githubusercontent.com/assets/20923036/24898922/271bf3de-1ea7-11e7-865a-b095f3fcf260.jpg)

After the "correction of rights" in the account control panel - the work of the site is normalized until the next publication.
![444](https://cloud.githubusercontent.com/assets/20923036/24898931/2d2a1bd4-1ea7-11e7-9e6a-88be83d36211.jpg)

Example http://videoblic.ru/

**Comment by Alyona73** [comment]
some problem with - myyoya.ru   - u265375582 - #67

**Comment by Alienson402** [comment]
http://1webseo.ru/
![333](https://cloud.githubusercontent.com/assets/20923036/24899328/93f694ea-1ea8-11e7-8cff-131ce88c03bb.jpg)
